(() => {
const { createClient } = supabase;
const cfg=window.LEO_CONFIG||{};
const db=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_KEY);
const app=document.getElementById("app");
let state={user:null,profile:null,screen:"home",chat:null,profiles:[],messages:[],moments:JSON.parse(localStorage.getItem("leo_moments")||"[]"),notifications:JSON.parse(localStorage.getItem("leo_notifications")||"[]"),settings:JSON.parse(localStorage.getItem("leo_settings")||'{"messages":true,"calls":true,"moments":true}')};

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const toast=m=>{const d=document.createElement("div");d.className="toast";d.textContent=m;app.querySelector(".shell")?.appendChild(d);setTimeout(()=>d.remove(),2200)};
const icon=(x)=>`<span>${x}</span>`;
async function boot(){const {data:{session}}=await db.auth.getSession(); state.user=session?.user||null; if(state.user) await loadProfile(); render(); if(state.user) startPolling(); db.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;render()});}
async function loadProfile(){const {data}=await db.from("profiles").select("*").eq("id",state.user.id).maybeSingle();state.profile=data||null}
async function getProfiles(){const {data,error}=await db.from("profiles").select("*").order("display_name"); if(!error)state.profiles=data||[]}
async function getMessages(){if(!state.chat||!state.user)return; const a=state.user.id,b=state.chat.id; const {data}=await db.from("messages").select("*").or(`and(sender_id.eq.${a},receiver_id.eq.${b}),and(sender_id.eq.${b},receiver_id.eq.${a})`).order("created_at",{ascending:true}); if(data)state.messages=data}
let poll; function startPolling(){clearInterval(poll);poll=setInterval(async()=>{if(state.screen==="chat"){await getMessages();render()}},2500)}
function layout(inner,nav=true){return `<div class="app"><div class="shell">${inner}${nav?navBar():""}</div></div>`}
function navBar(){const n=[["home","💬","Chats"],["search","⌕","Search"],["moments","✦","Moments"],["calls","☎","Calls"],["settings","⚙","Settings"]];return `<div class="nav">${n.map(x=>`<button class="${state.screen===x[0]?'active':''}" onclick="go('${x[0]}')">${icon(x[1])}<b>${x[2]}</b></button>`).join("")}</div>`}
window.go=s=>{state.screen=s;render()};
window.openChat=async p=>{state.chat=p;state.screen="chat";await getMessages();render()};
window.logout=async()=>{await db.auth.signOut();state.user=null;state.profile=null;state.screen="home";render()};
function render(){if(!state.user){renderAuth();return} if(!state.profile){renderSetup();return} if(state.screen==="chat"){renderChat();return} if(state.screen==="search"){renderSearch();return} if(state.screen==="moments"){renderMoments();return} if(state.screen==="calls"){renderCalls();return} if(state.screen==="settings"){renderSettings();return} if(state.screen==="notifications"){renderNotifications();return} renderHome()}
function renderAuth(){app.innerHTML=layout(`<div class="screen center" style="justify-content:center;padding:28px"><img class="logo" src="./logo.svg"><h1>Leo Chat</h1><p class="muted">Chat. Connect. Roar.</p><input id="email" class="input" placeholder="Email" type="email"><input id="pass" class="input" placeholder="Password" type="password"><button class="btn" onclick="auth('signin')">Sign in</button><button class="btn secondary" onclick="auth('signup')">Create account</button></div>`,false)}
window.auth=async mode=>{const email=document.getElementById("email").value.trim(),password=document.getElementById("pass").value;if(!email||!password)return toast("Enter email and password");let r=mode==="signup"?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(r.error)return toast(r.error.message);state.user=r.data.user;await loadProfile();render()}
function renderSetup(){app.innerHTML=layout(`<div class="screen center" style="justify-content:center;padding:25px"><img class="logo" src="./logo.svg"><h2>Set up your Leo profile</h2><input id="uname" class="input" placeholder="Username"><input id="dname" class="input" placeholder="Display name"><button class="btn" onclick="saveProfile()">Enter Leo Chat</button></div>`,false)}
window.saveProfile=async()=>{const username=document.getElementById("uname").value.trim().toLowerCase(),display_name=document.getElementById("dname").value.trim();if(!username||!display_name)return toast("Complete your profile");const {data,error}=await db.from("profiles").insert({id:state.user.id,username,display_name,avatar:"🦁"}).select().single();if(error)return toast(error.message);state.profile=data;render()}
async function renderHome(){await getProfiles();const people=state.profiles.filter(p=>p.id!==state.user.id);app.innerHTML=layout(`<div class="screen"><div class="top"><div class="brand"><img src="./logo.svg">Leo Chat</div><button class="iconbtn" onclick="state.screen='notifications';render()">🔔</button></div><div class="content"><div class="card"><div class="row"><div class="avatar">🦁</div><div class="grow"><div class="name">${esc(state.profile.display_name)}</div><div class="sub">@${esc(state.profile.username)}</div></div></div></div><h3>People</h3>${people.length?people.map(p=>`<div class="listitem" onclick='openChat(${JSON.stringify(p)})'><div class="avatar">${esc(p.avatar||"🦁")}</div><div class="grow"><div class="name">${esc(p.display_name)}</div><div class="sub">@${esc(p.username)}</div></div><div class="gold">›</div></div>`).join(""):`<div class="empty">No other Leo users yet.</div>`}</div></div>`)}
function renderSearch(){app.innerHTML=layout(`<div class="screen"><div class="top"><div class="brand">${icon("⌕")}Search</div></div><div class="content"><input id="q" class="input search" placeholder="Search people..." oninput="filterPeople()"><div id="results"></div></div></div>`);filterPeople()}
async function filterPeople(){await getProfiles();const q=(document.getElementById("q")?.value||"").toLowerCase();const arr=state.profiles.filter(p=>p.id!==state.user.id&&(`${p.display_name} ${p.username}`).toLowerCase().includes(q));const r=document.getElementById("results");if(r)r.innerHTML=arr.map(p=>`<div class="listitem" onclick='openChat(${JSON.stringify(p)})'><div class="avatar">${esc(p.avatar||"🦁")}</div><div class="grow"><div class="name">${esc(p.display_name)}</div><div class="sub">@${esc(p.username)}</div></div></div>`).join("")||`<div class="empty">No matches.</div>`}
function renderChat(){const p=state.chat;const msgs=state.messages;app.innerHTML=layout(`<div class="chat"><div class="chathead"><button class="back" onclick="go('home')">‹</button><div class="avatar">${esc(p.avatar||"🦁")}</div><div class="grow"><div class="name">${esc(p.display_name)}</div><div class="sub">Leo Chat</div></div><button class="iconbtn" onclick="callUser('voice')">☎</button><button class="iconbtn" onclick="callUser('video')">▣</button></div><div class="messages" id="messages">${msgs.map(m=>{const image=m.message?.startsWith("LEO_IMAGE::");return `<div class="bubble ${m.sender_id===state.user.id?'mine':'theirs'}">${image?`<img src="${esc(m.message.slice(11))}">`:esc(m.message)}</div>`}).join("")||`<div class="empty">Start the conversation 🦁</div>`}</div><div class="composer"><label class="iconbtn" style="display:grid;place-items:center">＋<input id="photo" class="photo-btn" type="file" accept="image/*" onchange="sendPhoto(event)"></label><input id="msg" class="input" placeholder="Message..." onkeydown="if(event.key==='Enter')sendMsg()"><button class="send" onclick="sendMsg()">➤</button></div></div>`,false);setTimeout(()=>{const m=document.getElementById("messages");if(m)m.scrollTop=m.scrollHeight},20)}
window.sendMsg=async()=>{const el=document.getElementById("msg"),text=el.value.trim();if(!text)return;const {error}=await db.from("messages").insert({sender_id:state.user.id,receiver_id:state.chat.id,message:text});if(error)return toast(error.message);el.value="";await getMessages();renderChat()}
window.sendPhoto=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024)return toast("Photo must be under 4 MB");const rd=new FileReader();rd.onload=async()=>{const {error}=await db.from("messages").insert({sender_id:state.user.id,receiver_id:state.chat.id,message:"LEO_IMAGE::"+rd.result});if(error)return toast(error.message);await getMessages();renderChat()};rd.readAsDataURL(f)}
window.callUser=kind=>toast(`${kind==="video"?"Video":"Voice"} call screen ready — real calling needs WebRTC.`)
function renderMoments(){app.innerHTML=layout(`<div class="screen"><div class="top"><div class="brand">${icon("✦")}Moments</div><button class="iconbtn" onclick="document.getElementById('momentFile').click()">＋</button><input id="momentFile" class="photo-btn" type="file" accept="image/*" onchange="addMoment(event)"></div><div class="content">${state.moments.length?state.moments.map(m=>`<div class="moment"><img src="${esc(m.src)}"><p>${esc(m.text||"Leo Moment")}<br><span class="muted">${new Date(m.at).toLocaleString()}</span></p></div>`).join(""):`<div class="empty"><div style="font-size:50px">✦</div>No moments yet.</div>`}</div></div>`)}
window.addMoment=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const text=prompt("Moment caption")||"";state.moments.unshift({src:r.result,text,at:Date.now()});localStorage.setItem("leo_moments",JSON.stringify(state.moments));renderMoments()};r.readAsDataURL(f)}
function renderCalls(){app.innerHTML=layout(`<div class="screen"><div class="top"><div class="brand">${icon("☎")}Calls</div></div><div class="content"><div class="card center"><img class="logo" style="width:80px;height:80px" src="./logo.svg"><h2>Leo Calls</h2><p class="muted">Voice and video call controls are ready. A production call service/WebRTC connection is required for live audio and video.</p><button class="btn" onclick="toast('Choose a person from Chats to call')">Start a call</button></div></div></div>`)}
function renderSettings(){app.innerHTML=layout(`<div class="screen"><div class="top"><div class="brand">${icon("⚙")}Settings</div></div><div class="content"><div class="card"><h3>Profile</h3><div class="row"><div class="avatar">🦁</div><div class="grow"><div class="name">${esc(state.profile.display_name)}</div><div class="sub">@${esc(state.profile.username)}</div></div></div></div><div class="card"><h3>Notifications</h3>${settingRow("messages","Messages")} ${settingRow("calls","Calls")} ${settingRow("moments","Moments")}</div><button class="btn secondary" onclick="state.screen='notifications';render()">🔔 Notifications</button><button class="btn secondary" onclick="logout()">Log out</button></div></div>`)}
function settingRow(k,label){return `<div class="row" style="padding:10px 0;border-bottom:1px solid #222"><div class="grow">${label}</div><input class="switch" type="checkbox" ${state.settings[k]?'checked':''} onchange="toggleSetting('${k}',this.checked)"></div>`}
window.toggleSetting=(k,v)=>{state.settings[k]=v;localStorage.setItem("leo_settings",JSON.stringify(state.settings))}
function renderNotifications(){app.innerHTML=layout(`<div class="screen"><div class="top"><div class="brand"><button class="back" onclick="go('settings')">‹</button>${icon("🔔")}Notifications</div></div><div class="content">${state.notifications.length?state.notifications.map(n=>`<div class="card"><div class="name">${esc(n.title)}</div><div class="sub">${esc(n.body)}</div></div>`).join(""):`<div class="empty">No notifications yet.</div>`}</div></div>`)}
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
boot();
})();